[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
# startup_mode = "Maximized"
# opacity = 0.9
# blur = true

[window.dimensions]
columns = 142
lines = 40

[window.padding]
x = 3
y = 3

